CREATE TABLE ingredents
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    prefix VARCHAR(10),
    parent VARCHAR(100) NOT NULL,
    child_parent VARCHAR(100),
    usages INT NOT NULL,
);

-- Spices ////////////////////////////////////////////////////

INSERT INTO  ingredents (name, parent, child_parent, usages)
VALUES 
    ('Star Anise', 'Spices', NULL, 0),
    ('Ginger', 'Spices', NULL, 0),
    ('Sesame Seeds', 'Spices', NULL, 0),
    ('Cumin Seeds', 'Spices', NULL, 0),
    ('Garlic Powder', 'Spices', NULL, 0),
    ('Poppy Seeds White', 'Spices', NULL, 0),
    ('Poppy Seeds Blue', 'Spices', NULL, 0),
    ('Sesame Seeds Black', 'Spices', NULL, 0),
    ('Cinnamon', 'Spices', NULL, 0),
    ('Coriander Seeds', 'Spices', NULL, 0),
    ('Cardamom Pods', 'Spices', NULL, 0),
    ('Mustard Seeds', 'Spices', NULL, 0),
    ('Nutmeg', 'Spices', NULL, 0),
    ('Allspice', 'Spices', NULL, 0),
    ('Fennel', 'Spices', NULL, 0),
    ('Dill', 'Spices', NULL, 0),
    ('Vannilla Beans', 'Spices', NULL, 0),
    ('Imitation Vannilla', 'Spices', NULL, 0),
    ('Saffron', 'Spices', NULL, 0),
    ('Black Pepper', 'Spices', NULL, 0),
    ('White Pepper', 'Spices', NULL, 0),
    ('Cayenne Pepper', 'Spices', NULL, 0),
    ('Onion Powder', 'Spices', NULL, 0),
    ('Tumeric Powder', 'Spices', NULL, 0);


-- Herbs ///////////////////////////////////////////////////

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Basil', 'Herbs', NULL, 0),
    ('Lavender', 'Herbs', NULL, 0),
    ('Chives', 'Herbs', NULL, 0),
    ('Peppermint', 'Herbs', NULL, 0),
    ('Mint', 'Herbs', NULL, 0),
    ('Spearmint', 'Herbs', NULL, 0),
    ('Sage', 'Herbs', NULL, 0),
    ('Cilantro', 'Herbs', NULL, 0),
    ('Parsley', 'Herbs', NULL, 0),
    ('Oregano', 'Herbs', NULL, 0),
    ('Cherivil', 'Herbs', NULL, 0),
    ('Bay leaves', 'Herbs', NULL, 0),
    ('Thyme', 'Herbs', NULL, 0),
    ('Marjoram', 'Herbs', NULL, 0),
    ('Dill Weed', 'Herbs', NULL, 0),
    ('Rosmary', 'Herbs', NULL, 0),
    ('Tarragon', 'Herbs', NULL, 0),
    ('Sumac', 'Herbs', NULL, 0),
    ('Fanugreek', 'Herbs', NULL, 0),
    ('Markrut Lime Leaves', 'Herbs', NULL, 0),
    ('Lemon Grass', 'Herbs', NULL, 0),
    ('Fennel', 'Herbs', NULL, 0);


-- Condiments Oils and Sauces ///////////////////////////////

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Olive Oil', 'Condiments, Oils & Sauces', NULL, 0),
    ('Avacado Oil', 'Condiments, Oils & Sauces', NULL, 0),
    ('Vegtable Oil', 'Condiments, Oils & Sauces', NULL, 0),
    ('Ketchup', 'Condiments, Oils & Sauces', NULL, 0),
    ('Mustard', 'Condiments, Oils & Sauces', NULL, 0),
    ('Soy Sauce', 'Condiments, Oils & Sauces', NULL, 0),
    ('Vinager', 'Condiments, Oils & Sauces', NULL, 0),
    ('White Vinager', 'Condiments, Oils & Sauces', NULL, 0),
    ('Apple Cider Vinager', 'Condiments, Oils & Sauces', NULL, 0),
    ('Rice Vinager', 'Condiments, Oils & Sauces', NULL, 0);


-- Grains ////////////////////////////////////////////////////
-- Breads

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Arepa Bread', 'Grains', 'Breads', 0),
    ('Babka Bread', 'Grains', 'Breads', 0),
    ('Bagels', 'Grains', 'Breads', 0),
    ('Bauguette', 'Grains', 'Breads', 0),
    ('Banana Bread', 'Grains', 'Breads', 0),
    ('Bao Buns', 'Grains', 'Breads', 0),
    ('Beer Bread', 'Grains', 'Breads', 0),
    ('Brioche Bread', 'Grains', 'Breads', 0),
    ('Brown Bread', 'Grains', 'Breads', 0),
    ('Cibatta Bread', 'Grains', 'Breads', 0),
    ('Challah Bread', 'Grains', 'Breads', 0),
    ('Cloud Bread', 'Grains', 'Breads', 0),
    ('Corn Bread', 'Grains', 'Breads', 0),
    ('Crumpets', 'Grains', 'Breads', 0),
    ('English Muffins', 'Grains', 'Breads', 0),
    ('Flat Bread', 'Grains', 'Breads', 0),
    ('Focaccia Bread', 'Grains', 'Breads', 0),
    ('Hokkaido Bread', 'Grains', 'Breads', 0),
    ('Irish Soda Bread', 'Grains', 'Breads', 0),
    ('Italian Bread', 'Grains', 'Breads', 0),
    ('Multigrain Bread', 'Grains', 'Breads', 0),
    ('Naan Bread', 'Grains', 'Breads', 0),
    ('Paratha Bread', 'Grains', 'Breads', 0),
    ('Pita Bread', 'Grains', 'Breads', 0),
    ('Potato Bread', 'Grains', 'Breads', 0),
    ('Pumpernickle Bread', 'Grains', 'Breads', 0),
    ('Rye Bread', 'Grains', 'Breads', 0),
    ('White Sliced Bread', 'Grains', 'Breads', 0),
    ('Wheat Sliced Bread', 'Grains', 'Breads', 0),
    ('Sourdough Bread', 'Grains', 'Breads', 0),
    ('Sprouted Grain Bread', 'Grains', 'Breads', 0);

-- Rice

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Ariborio Rice', 'Grains', 'Rice', 0),
    ('Aromatic Rice', 'Grains', 'Rice', 0),
    ('Basmati 370 Rice', 'Grains', 'Rice', 0),
    ('Basmati Rice', 'Grains', 'Rice', 0),
    ('Bhutanese Red Rice', 'Grains', 'Rice', 0),
    ('Bhutanese White Rice', 'Grains', 'Rice', 0),
    ('Biryani Rice', 'Grains', 'Rice', 0),
    ('Black Rice', 'Grains', 'Rice', 0),
    ('Bomba Rice', 'Grains', 'Rice', 0),
    ('Brown Basmati Rice', 'Grains', 'Rice', 0),
    ('Brown Rice', 'Grains', 'Rice', 0),
    ('California Blonde Rice', 'Grains', 'Rice', 0),
    ('Calrose Rice', 'Grains', 'Rice', 0),
    ('Camargue Red Rice', 'Grains', 'Rice', 0),
    ('Carnaroli Rice', 'Grains', 'Rice', 0),
    ('Colusari Red Rice', 'Grains', 'Rice', 0),
    ('Doongara Rice', 'Grains', 'Rice', 0),
    ('Egyptian Black Rice', 'Grains', 'Rice', 0),
    ('Egyptian Rice', 'Grains', 'Rice', 0),
    ('Black Sticky Rice', 'Grains', 'Rice', 0),
    ('Brown Sticky Rice', 'Grains', 'Rice', 0),
    ('Green Jade Bamboo Rice', 'Grains', 'Rice', 0),
    ('Himalayan Red Rice', 'Grains', 'Rice', 0),
    ('Indonesian Black Rice', 'Grains', 'Rice', 0),
    ('Italian Black Rice (Venere Rice)', 'Grains', 'Rice', 0),
    ('Jade Pearl Rice', 'Grains', 'Rice', 0),
    ('Jasmine Rice', 'Grains', 'Rice', 0),
    ('Kokuho Rose Rice', 'Grains', 'Rice', 0),
    ('Koshihikara Rice', 'Grains', 'Rice', 0),
    ('Mochi Rice (Sweet Rice)', 'Grains', 'Rice', 0),
    ('Parboiled Rice', 'Grains', 'Rice', 0),
    ('Ponni Rice', 'Grains', 'Rice', 0),
    ('Purple Sticky Rice', 'Grains', 'Rice', 0),
    ('Red Rice', 'Grains', 'Rice', 0),
    ('Red Cargo Rice', 'Grains', 'Rice', 0),
    ('Riceberry Rice', 'Grains', 'Rice', 0),
    ('Rosanero Rice', 'Grains', 'Rice', 0),
    ('Saudee Rice', 'Grains', 'Rice', 0),
    ('Sinandomeng Rice', 'Grains', 'Rice', 0),
    ('Sticky Rice', 'Grains', 'Rice', 0),
    ('Sushi Rice', 'Grains', 'Rice', 0),
    ('Texmati Rice', 'Grains', 'Rice', 0),
    ('Valencia Rice', 'Grains', 'Rice', 0),
    ('Wehani Rice', 'Grains', 'Rice', 0),
    ('White Rice', 'Grains', 'Rice', 0),
    ('Wild Rice', 'Grains', 'Rice', 0);


-- Flours

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES 
    ('Acorn Flour', 'Grains', 'Flours', 0),
    ('Almond Flour', 'Grains', 'Flours', 0),
    ('Amaranth Flour', 'Grains', 'Flours', 0),
    ('Arrowroot Flour', 'Grains', 'Flours', 0),
    ('Barley Flour', 'Grains', 'Flours', 0),
    ('Bread Flour', 'Grains', 'Flours', 0),
    ('Brown Rice Flour', 'Grains', 'Flours', 0),
    ('Buckwheat Flour', 'Grains', 'Flours', 0),
    ('Cassava Flour', 'Grains', 'Flours', 0),
    ('Chestnut Flour', 'Grains', 'Flours', 0),
    ('Chickpea Flour', 'Grains', 'Flours', 0),
    ('Coconut Flour', 'Grains', 'Flours', 0),
    ('Corn Flour', 'Grains', 'Flours', 0),
    ('Cricket Flour', 'Grains', 'Flours', 0),
    ('High Gluten Flour', 'Grains', 'Flours', 0),
    ('Kamut Flour', 'Grains', 'Flours', 0),
    ('Lupin Flour', 'Grains', 'Flours', 0),
    ('Millit Flour', 'Grains', 'Flours', 0),
    ('Oat Flour', 'Grains', 'Flours', 0),
    ('Pastry Flour', 'Grains', 'Flours', 0),
    ('Peanut Flour', 'Grains', 'Flours', 0),
    ('Potato Flour', 'Grains', 'Flours', 0),
    ('Quinoa Flour', 'Grains', 'Flours', 0),
    ('Red Lentil Flour', 'Grains', 'Flours', 0),
    ('Rye Flour', 'Grains', 'Flours', 0),
    ('Self-Rising Flour', 'Grains', 'Flours', 0),
    ('Semolina Flour', 'Grains', 'Flours', 0),
    ('Sorghum Flour', 'Grains', 'Flours', 0),
    ('Sesame Flour', 'Grains', 'Flours', 0),
    ('Soy Flour', 'Grains', 'Flours', 0),
    ('Spelt Flour', 'Grains', 'Flours', 0),
    ('Sunflower Seed Flour', 'Grains', 'Flours', 0),
    ('Tapioca Flour', 'Grains', 'Flours', 0),
    ('Teff Flour', 'Grains', 'Flours', 0),
    ('All Purpose Flour', 'Grains', 'Flours', 0),
    ('White Rice Flour', 'Grains', 'Flours', 0),
    ('Whole Wheat Flour', 'Grains', 'Flours', 0);

-- Pasta

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES  
    ('Angle Hair', 'Grains', 'Pasta', 0),
    ('Bucantini', 'Grains', 'Pasta', 0),
    ('Campanelle', 'Grains', 'Pasta', 0),
    ('Cannelloni', 'Grains', 'Pasta', 0),
    ('Cappalletti', 'Grains', 'Pasta', 0),
    ('Carmamelle', 'Grains', 'Pasta', 0),
    ('Casarecce', 'Grains', 'Pasta', 0),
    ('Cascatelli', 'Grains', 'Pasta', 0),
    ('Cavatappi', 'Grains', 'Pasta', 0),
    ('Cacatelli', 'Grains', 'Pasta', 0),
    ('Conchiglie', 'Grains', 'Pasta', 0),
    ('Ditalini', 'Grains', 'Pasta', 0),
    ('Egg noodles', 'Grains', 'Pasta', 0),
    ('Elbows', 'Grains', 'Pasta', 0),
    ('Farafelle', 'Grains', 'Pasta', 0),
    ('Faux Pasta', 'Grains', 'Pasta', 0),
    ('Fettuccine', 'Grains', 'Pasta', 0),
    ('Fileja', 'Grains', 'Pasta', 0),
    ('Fiori', 'Grains', 'Pasta', 0),
    ('Fusilli', 'Grains', 'Pasta', 0),
    ('Garganelli', 'Grains', 'Pasta', 0),
    ('Gemelli', 'Grains', 'Pasta', 0),
    ('Gnocchi', 'Grains', 'Pasta', 0),
    ('Jumbo Shells', 'Grains', 'Pasta', 0),
    ('Lasagna', 'Grains', 'Pasta', 0),
    ('Linguine', 'Grains', 'Pasta', 0),
    ('Macaroni', 'Grains', 'Pasta', 0),
    ('Mafaldine', 'Grains', 'Pasta', 0),
    ('Manicotti', 'Grains', 'Pasta', 0),
    ('Mezzelune', 'Grains', 'Pasta', 0),
    ('Orecchiette', 'Grains', 'Pasta', 0),
    ('Orzo', 'Grains', 'Pasta', 0),
    ('Paccheri', 'Grains', 'Pasta', 0),
    ('Papparedelle', 'Grains', 'Pasta', 0),
    ('Passatelli', 'Grains', 'Pasta', 0),
    ('Pastina', 'Grains', 'Pasta', 0),
    ('Penne', 'Grains', 'Pasta', 0),
    ('Pici', 'Grains', 'Pasta', 0),
    ('Radiatori', 'Grains', 'Pasta', 0),
    ('Ravioli', 'Grains', 'Pasta', 0),
    ('Rigatoni', 'Grains', 'Pasta', 0),
    ('Rotelle', 'Grains', 'Pasta', 0),
    ('Rotini', 'Grains', 'Pasta', 0),
    ('Stelle', 'Grains', 'Pasta', 0),
    ('Spaghetti', 'Grains', 'Pasta', 0),
    ('Tagliatelle', 'Grains', 'Pasta', 0),
    ('Testaroli', 'Grains', 'Pasta', 0),
    ('Tortellini', 'Grains', 'Pasta', 0),
    ('Vermicelli', 'Grains', 'Pasta', 0),
    ('Ziti', 'Grains', 'Pasta', 0);

-- Dairy & Non Dairy /////////////////////////////////////////
-- Milks

INSERT INTO ingredents (name, prefix, parent, child_parent, usages)
VALUES 
    ('Whole Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('1% Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('2% Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Skim Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Channel Island Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Chocolate Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('UTH Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Lactose Free Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Butter Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Evaporated Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Goat Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Milk Powder (Whole)', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Milk Powder (Skim)', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Condensed Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0),
    ('Almond Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Cashew Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Coaconut Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Hazelnut Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Hemp Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Oat Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Pea Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Rice Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Soy Milk', 'Non-Dairy', 'Dairy & Non Dairy', 'Milks', 0),
    ('Toned Milk', NULL, 'Dairy & Non Dairy', 'Milks', 0);

-- Creams & Butters

INSERT INTO ingredents (name, prefix, parent, child_parent, usages)
VALUES
    ('Unsalted Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Salted Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Sweet Cream Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Ghee', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Organic Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Plant-Based Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Grass Fed Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('European Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Margarine', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Whipped Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Goat Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Smen Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Amish Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Compound Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Browned Butter', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Heavy Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Light Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Half & Half', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Whipping Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Sour Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Creme Fraiche', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Clotted Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Chantilly Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Long Life Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Goat Milk Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Reduced Fat Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0),
    ('Low Fat Cream', NULL, 'Dairy & Non Dairy', 'Creams & Butters', 0);

-- Cheeses

INSERT INTO ingredents (name, prefix, parent, child_parent, usages)
VALUES
    ('Goverment Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('American Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Asiago', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Blue Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Brocconcini', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Brie', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Burrata', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('ButterKase', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Cabrales', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Camembert', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Cheddar', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Colby', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Colby Jack', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Cheddar Jack', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Cotija', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Cottage Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Cream Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Danish Blue (Danablu)', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Edam', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Emmental', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Feta', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Fontina', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Goat Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Gorgonzola', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Gouda', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Grana Padano', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Gruyere', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Halloumi', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Havarti', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Harudka', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Jarlsberg', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Manchego', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Marscarpone', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Montery Jack', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Mozzarella', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Muenster', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Noufchatel', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Paneer', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Parmesan', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Parmigiano Reggiano', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Pecorino Romano', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Pepper Jack', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Processed', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Provolone', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Quark', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Queso Blanco', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Queso Fresco', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Raclette', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Ricotta', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Romano', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Roquefort', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Sakura', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Sirene', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Stiltion', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('String Cheese', NULL, 'Dairy & Non Dairy', 'Cheeses', 0),
    ('Swiss', NULL, 'Dairy & Non Dairy', 'Cheeses', 0);

-- Meats /////////////////////////////////////////////////////
-- Beef

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Chuck 7-Bone', 'Meats', 'Beef', 0),
    ('Chuck Pot Roast', 'Meats', 'Beef', 0),
    ('Chuck Steak', 'Meats', 'Beef', 0),
    ('Chuck Eye Steak', 'Meats', 'Beef', 0),
    ('Sholder Top Blade', 'Meats', 'Beef', 0),
    ('Sholder Pot Roast', 'Meats', 'Beef', 0),
    ('Sholder Steak', 'Meats', 'Beef', 0),
    ('Sholder Center', 'Meats', 'Beef', 0),
    ('Sholder Petite', 'Meats', 'Beef', 0),
    ('sholder Petite Tender', 'Meats', 'Beef', 0),
    ('Boneless Short Ribs', 'Meats', 'Beef', 0),
    ('Rib Roast', 'Meats', 'Beef', 0),
    ('Rib Steak', 'Meats', 'Beef', 0),
    ('Back Ribs', 'Meats', 'Beef', 0),
    ('Porterhouse', 'Meats', 'Beef', 0),
    ('T-bone Steak', 'Meats', 'Beef', 0),
    ('Tender Loin Roast', 'Meats', 'Beef', 0),
    ('Tenderloin Steak', 'Meats', 'Beef', 0),
    ('Tri-tip Roast', 'Meats', 'Beef', 0),
    ('Tri-tip Steak', 'Meats', 'Beef', 0),
    ('Top Sirloin Steak', 'Meats', 'Beef', 0),
    ('Top Round Steak', 'Meats', 'Beef', 0),
    ('Bottom Round Roast', 'Meats', 'Beef', 0),
    ('Bottom Round Steak', 'Meats', 'Beef', 0),
    ('Eye Round Roast', 'Meats', 'Beef', 0),
    ('Eye Round Steak', 'Meats', 'Beef', 0),
    ('Round Tip Roast', 'Meats', 'Beef', 0),
    ('Round Tip Steak', 'Meats', 'Beef', 0),
    ('Sirloin Tip Center Roast', 'Meats', 'Beef', 0),
    ('Sirloin Tip Center Steak', 'Meats', 'Beef', 0),
    ('Sirloin Tip Side Steak', 'Meats', 'Beef', 0),
    ('Shank Cross Cut', 'Meats', 'Beef', 0),
    ('Brisket Flat Cut', 'Meats', 'Beef', 0),
    ('Skirt Steak', 'Meats', 'Beef', 0),
    ('Flank Steak', 'Meats', 'Beef', 0),
    ('Ground Beef', 'Meats', 'Beef', 0),
    ('Cubed Steak', 'Meats', 'Beef', 0),
    ('Beef Stew Meat', 'Meats', 'Beef', 0),
    ('Beef kabobs', 'Meats', 'Beef', 0),
    ('Stirfry / Fajita Beef', 'Meats', 'Beef', 0);

-- Poultry

INSERT INTO ingredents (name, Prefix, parent, child_parent, usages)
VALUES
    ('Whole', 'Chicken', 'Meats', 'Poultry', 0),
    ('Boneless Breast', 'Chicken', 'Meats', 'Poultry', 0),
    ('Bone-in Breast', 'Chicken', 'Meats', 'Poultry', 0),
    ('Thigh', 'Chicken', 'Meats', 'Poultry', 0),
    ('Drumsticks', 'Chicken', 'Meats', 'Poultry', 0),
    ('Wings', 'Chicken', 'Meats', 'Poultry', 0),
    ('Tenderloin', 'Chicken', 'Meats', 'Poultry', 0),
    ('Liver', 'Chicken', 'Meats', 'Poultry', 0),
    ('Heart', 'Chicken', 'Meats', 'Poultry', 0),
    ('Neck', 'Chicken', 'Meats', 'Poultry', 0),
    ('Back', 'Chicken', 'Meats', 'Poultry', 0),
    ('Feet', 'Chicken', 'Meats', 'Poultry', 0),
    ('Whole', 'Duck', 'Meats', 'Poultry', 0),
    ('Boneless Breast', 'Duck', 'Meats', 'Poultry', 0),
    ('Bone-in Breast', 'Duck', 'Meats', 'Poultry', 0),
    ('Thigh', 'Duck', 'Meats', 'Poultry', 0),
    ('Drumsticks', 'Duck', 'Meats', 'Poultry', 0),
    ('Wings', 'Duck', 'Meats', 'Poultry', 0),
    ('Tenderloin', 'Duck', 'Meats', 'Poultry', 0),
    ('Liver', 'Duck', 'Meats', 'Poultry', 0),
    ('Heart', 'Duck', 'Meats', 'Poultry', 0),
    ('Neck', 'Duck', 'Meats', 'Poultry', 0),
    ('Back', 'Duck', 'Meats', 'Poultry', 0),
    ('Feet', 'Duck', 'Meats', 'Poultry', 0),
    ('Whole', 'Turkey', 'Meats', 'Poultry', 0),
    ('Boneless Breast', 'Turkey', 'Meats', 'Poultry', 0),
    ('Bone-in Breast', 'Turkey', 'Meats', 'Poultry', 0),
    ('Thigh', 'Turkey', 'Meats', 'Poultry', 0),
    ('Drumsticks', 'Turkey', 'Meats', 'Poultry', 0),
    ('Wings', 'Turkey', 'Meats', 'Poultry', 0),
    ('Tenderloin', 'Turkey', 'Meats', 'Poultry', 0),
    ('Liver', 'Turkey', 'Meats', 'Poultry', 0),
    ('Heart', 'Turkey', 'Meats', 'Poultry', 0),
    ('Neck', 'Turkey', 'Meats', 'Poultry', 0),
    ('Back', 'Turkey', 'Meats', 'Poultry', 0),
    ('Feet', 'Turkey', 'Meats', 'Poultry', 0),
    ('Whole', 'Geese', 'Meats', 'Poultry', 0),
    ('Boneless Breast', 'Geese', 'Meats', 'Poultry', 0),
    ('Bone-in Breast', 'Geese', 'Meats', 'Poultry', 0),
    ('Thigh', 'Geese', 'Meats', 'Poultry', 0),
    ('Drumsticks', 'Geese', 'Meats', 'Poultry', 0),
    ('Wings', 'Geese', 'Meats', 'Poultry', 0),
    ('Tenderloin', 'Geese', 'Meats', 'Poultry', 0),
    ('Liver', 'Geese', 'Meats', 'Poultry', 0),
    ('Heart', 'Geese', 'Meats', 'Poultry', 0),
    ('Neck', 'Geese', 'Meats', 'Poultry', 0),
    ('Back', 'Geese', 'Meats', 'Poultry', 0),
    ('Feet', 'Geese', 'Meats', 'Poultry', 0);

-- Pork

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('', 'Meats', 'Pork', 0),

-- Eggs

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Chicken Eggs', 'Meats', 'Eggs', 0),
    ('Quail Eggs', 'Meats', 'Eggs', 0),
    ('Duck Eggs', 'Meats', 'Eggs', 0),
    ('Caviar', 'Meats', 'Eggs', 0),
    ('Goose Eggs', 'Meats', 'Eggs', 0),
    ('Turkey Eggs', 'Meats', 'Eggs', 0),
    ('EMU Eggs', 'Meats', 'Eggs', 0),
    ('Hilsa Eggs', 'Meats', 'Eggs', 0),
    ('Ostrich Eggs', 'Meats', 'Eggs', 0),
    ('Bantam Eggs', 'Meats', 'Eggs', 0);

-- Sea Food

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('', 'Meats', 'Sea Food', 0),

-- Processed

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('', 'Meats', 'Processed', 0),


-- Fruits /////////////////////////////////////////////////

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Apples', 'Fruits', NULL, 0),
    ('Açaí', 'Fruits', NULL, 0),
    ('Acerola Cherries', 'Fruits', NULL, 0),
    ('African Breadfruit', 'Fruits', NULL, 0),
    ('Akebi Fruit', 'Fruits', NULL, 0),
    ('Alpine Strawberry', 'Fruits', NULL, 0),
    ('African Mango', 'Fruits', NULL, 0),
    ('Amanatsu Oranges', 'Fruits', NULL, 0),
    ('Ambarella', 'Fruits', NULL, 0),
    ('Amaou Strawberries', 'Fruits', NULL, 0),
    ('Ambrosia Apples', 'Fruits', NULL, 0),
    ('Ambrosia Melon', 'Fruits', NULL, 0),
    ('Amla', 'Fruits', NULL, 0),
    ('Apricots', 'Fruits', NULL, 0),
    ('Annatto', 'Fruits', NULL, 0),
    ('Annona', 'Fruits', NULL, 0),
    ('Asian Pears', 'Fruits', NULL, 0),
    ('Arava Melon', 'Fruits', NULL, 0),
    ('Asam Kumbang', 'Fruits', NULL, 0),
    ('Avocado', 'Fruits', NULL, 0),
    ('Babaco', 'Fruits', NULL, 0),
    ('Bacuri Fruit', 'Fruits', NULL, 0),
    ('Balsam Apples', 'Fruits', NULL, 0),
    ('Barbados Cherries', 'Fruits', NULL, 0),
    ('Barberries', 'Fruits', NULL, 0),
    ('Batuan', 'Fruits', NULL, 0),
    ('Batuan', 'Fruits', NULL, 0),
    ('Beach Plums', 'Fruits', NULL, 0),
    ('Bearberries', 'Fruits', NULL, 0),
    ('Beechnut', 'Fruits', NULL, 0),
    ('Bell Peppers', 'Fruits', NULL, 0),
    ('Betel Nut', 'Fruits', NULL, 0),
    ('Bilberries', 'Fruits', NULL, 0),
    ('Biriba', 'Fruits', NULL, 0),
    ('Bitter Melon', 'Fruits', NULL, 0),
    ('Black Apples', 'Fruits', NULL, 0),
    ('Blackberries', 'Fruits', NULL, 0),
    ('Black Cherries', 'Fruits', NULL, 0),
    ('Black Currant', 'Fruits', NULL, 0),
    ('Black Mulberry', 'Fruits', NULL, 0),
    ('Black Raspberries', 'Fruits', NULL, 0),
    ('Black Sapote', 'Fruits', NULL, 0),
    ('Blood Lime', 'Fruits', NULL, 0),
    ('Blood Orange', 'Fruits', NULL, 0),
    ('Blue Dragon Fruit', 'Fruits', NULL, 0),
    ('Blue Java Banana', 'Fruits', NULL, 0),
    ('Blue Marble Fruit', 'Fruits', NULL, 0),
    ('Blue Olive', 'Fruits', NULL, 0),
    ('Blue Pearmain Apple', 'Fruits', NULL, 0),
    ('Blue Sausage Fruit', 'Fruits', NULL, 0),
    ('Blue Watermelon', 'Fruits', NULL, 0),
    ('Blueberries', 'Fruits', NULL, 0),
    ('Bottle Gourd', 'Fruits', NULL, 0),
    ('Boysenberry', 'Fruits', NULL, 0),
    ('Brazilian Guava', 'Fruits', NULL, 0),
    ('Brazil Nut', 'Fruits', NULL, 0),
    ('Breadfruit', 'Fruits', NULL, 0),
    ('Brush Cherry', 'Fruits', NULL, 0),
    ('Cabernet Sauvignon Grape', 'Fruits', NULL, 0),
    ('Calabash', 'Fruits', NULL, 0),
    ('Camu Camu Berry', 'Fruits', NULL, 0),
    ('Canary Fruit', 'Fruits', NULL, 0),
    ('Canistel Fruit', 'Fruits', NULL, 0),
    ('Cantaloupe', 'Fruits', NULL, 0),
    ('Caper Berry', 'Fruits', NULL, 0),
    ('Carambola', 'Fruits', NULL, 0),
    ('Carob', 'Fruits', NULL, 0),
    ('Cavendish Banana', 'Fruits', NULL, 0),
    ('Cedar Bay Cherry', 'Fruits', NULL, 0),
    ('Cempedak', 'Fruits', NULL, 0),
    ('Cherry', 'Fruits', NULL, 0),
    ('Chinese Quince', 'Fruits', NULL, 0),
    ('Chinese White Pear', 'Fruits', NULL, 0),
    ('Chinoto Sour Orange', 'Fruits', NULL, 0),
    ('Churchland Pear', 'Fruits', NULL, 0),
    ('Citron', 'Fruits', NULL, 0),
    ('Clementine', 'Fruits', NULL, 0),
    ('Cleopatra Mandarin', 'Fruits', NULL, 0),
    ('Coconut', 'Fruits', NULL, 0),
    ('Coco plum', 'Fruits', NULL, 0),
    ('Conference Pear', 'Fruits', NULL, 0),
    ('Cornelian Cherry', 'Fruits', NULL, 0),
    ('Cortland Apple', 'Fruits', NULL, 0),
    ('Cosmic Crisp Apple', 'Fruits', NULL, 0),
    ('Courgette', 'Fruits', NULL, 0),
    ('Crab Apple', 'Fruits', NULL, 0),
    ('Cranberry', 'Fruits', NULL, 0),
    ('Crimson Delight Apple', 'Fruits', NULL, 0),
    ('Crimson Gold Apple', 'Fruits', NULL, 0),
    ('Crispin Apple', 'Fruits', NULL, 0),
    ('Cucumber', 'Fruits', NULL, 0),
    ('Custard Apple', 'Fruits', NULL, 0),
    ('Dabai Fruit', 'Fruits', NULL, 0),
    ('Dangle Berry', 'Fruits', NULL, 0),
    ('Damson Plums', 'Fruits', NULL, 0),
    ('Darling Plum', 'Fruits', NULL, 0),
    ('Darwin’s Barberries', 'Fruits', NULL, 0),
    ('Date Plums', 'Fruits', NULL, 0),
    ('Davidson’s Plums', 'Fruits', NULL, 0),
    ('Dates', 'Fruits', NULL, 0),
    ('Dead Man’s Finger', 'Fruits', NULL, 0),
    ('Dekopon', 'Fruits', NULL, 0),
    ('Dessert Banana', 'Fruits', NULL, 0),
    ('Desert Fig', 'Fruits', NULL, 0),
    ('Desert Lime', 'Fruits', NULL, 0),
    ('Desert Quandong', 'Fruits', NULL, 0),
    ('Dewberries', 'Fruits', NULL, 0),
    ('Dinosaur Eggs', 'Fruits', NULL, 0),
    ('Discovery Apple', 'Fruits', NULL, 0),
    ('Dodder Laurel', 'Fruits', NULL, 0),
    ('Double Coconut', 'Fruits', NULL, 0),
    ('Dracontomelon', 'Fruits', NULL, 0),
    ('Dragon Fruit', 'Fruits', NULL, 0),
    ('Duku Fruit', 'Fruits', NULL, 0),
    ('Durian', 'Fruits', NULL, 0),
    ('Emu Berry Fruit', 'Fruits', NULL, 0),
    ('Enterprise Apple', 'Fruits', NULL, 0),
    ('Evergreen Huckleberry', 'Fruits', NULL, 0),
    ('Eggplant', 'Fruits', NULL, 0),
    ('Elephant Apple (Chalta)', 'Fruits', NULL, 0),
    ('Etrog', 'Fruits', NULL, 0),
    ('Elderberry', 'Fruits', NULL, 0),
    ('Emu Apple Fruit', 'Fruits', NULL, 0),
    ('Emblica', 'Fruits', NULL, 0),
    ('European Pear', 'Fruits', NULL, 0),
    ('Eastern Hawthorn Fruit', 'Fruits', NULL, 0),
    ('Egg Fruit', 'Fruits', NULL, 0),
    ('Early Gold Mango', 'Fruits', NULL, 0),
    ('Entawak', 'Fruits', NULL, 0),
    ('Elands Sour Fig', 'Fruits', NULL, 0),
    ('Ensete', 'Fruits', NULL, 0),
    ('Early Girl Tomato', 'Fruits', NULL, 0),
    ('Fairchild Tangerines', 'Fruits', NULL, 0),
    ('False Mastic Fruit', 'Fruits', NULL, 0),
    ('Farkleberry', 'Fruits', NULL, 0),
    ('Fascell Mango', 'Fruits', NULL, 0),
    ('Fazli Mango', 'Fruits', NULL, 0),
    ('Feijoa', 'Fruits', NULL, 0),
    ('Fe’I Banana', 'Fruits', NULL, 0),
    ('Fibrous Satinash Fruit', 'Fruits', NULL, 0),
    ('Figs', 'Fruits', NULL, 0),
    ('Finger Lime', 'Fruits', NULL, 0),
    ('Five Flavor Berry', 'Fruits', NULL, 0),
    ('Flatwoods Plum', 'Fruits', NULL, 0),
    ('Florida Cherry', 'Fruits', NULL, 0),
    ('Forest Strawberries', 'Fruits', NULL, 0),
    ('Fox Grapes', 'Fruits', NULL, 0),
    ('Fuji Apples', 'Fruits', NULL, 0),
    ('Fukushu Kumquat', 'Fruits', NULL, 0),
    ('Gala Apple', 'Fruits', NULL, 0),
    ('Galia Melon', 'Fruits', NULL, 0),
    ('Gamboge', 'Fruits', NULL, 0),
    ('Genip', 'Fruits', NULL, 0),
    ('Giant Lau Lau', 'Fruits', NULL, 0),
    ('Goji Berry', 'Fruits', NULL, 0),
    ('Golden Apple', 'Fruits', NULL, 0),
    ('Golden Delicious Apple', 'Fruits', NULL, 0),
    ('Golden Kiwi', 'Fruits', NULL, 0),
    ('Gooseberry', 'Fruits', NULL, 0),
    ('Gorham Pear', 'Fruits', NULL, 0),
    ('Goumi', 'Fruits', NULL, 0),
    ('Governor’s Plum', 'Fruits', NULL, 0),
    ('Granadilla', 'Fruits', NULL, 0),
    ('Grand Nain Banana', 'Fruits', NULL, 0),
    ('Granny Smith Apple', 'Fruits', NULL, 0),
    ('Grapefruit', 'Fruits', NULL, 0),
    ('Grape', 'Fruits', NULL, 0),
    ('Greek Fig', 'Fruits', NULL, 0),
    ('Green Adjou Pear', 'Fruits', NULL, 0),
    ('Green Apple', 'Fruits', NULL, 0),
    ('Green Banana', 'Fruits', NULL, 0),
    ('Green Bell Pepper', 'Fruits', NULL, 0),
    ('Green Egg Squash', 'Fruits', NULL, 0),
    ('Green Fig', 'Fruits', NULL, 0),
    ('Green Gage Plum', 'Fruits', NULL, 0),
    ('Green Grapes', 'Fruits', NULL, 0),
    ('Green Lemon', 'Fruits', NULL, 0),
    ('Green Raisins', 'Fruits', NULL, 0),
    ('Green Strawberry', 'Fruits', NULL, 0),
    ('Green Tomato', 'Fruits', NULL, 0),
    ('Ground Plum', 'Fruits', NULL, 0),
    ('Grosella Negra', 'Fruits', NULL, 0),
    ('Grumichama', 'Fruits', NULL, 0),
    ('Guarana.', 'Fruits', NULL, 0),
    ('Guava', 'Fruits', NULL, 0),
    ('Guavaberry', 'Fruits', NULL, 0),
    ('Hackberry', 'Fruits', NULL, 0),
    ('Hala Fruit', 'Fruits', NULL, 0),
    ('Hardy Kiwi', 'Fruits', NULL, 0),
    ('Hawaiian Mountain Apples', 'Fruits', NULL, 0),
    ('Hawthorn Fruit', 'Fruits', NULL, 0),
    ('Hazelnuts', 'Fruits', NULL, 0),
    ('Heirloom Tomatoes', 'Fruits', NULL, 0),
    ('Highbush Blueberries', 'Fruits', NULL, 0),
    ('Highbush Cranberries', 'Fruits', NULL, 0),
    ('Himalayan Mulberries', 'Fruits', NULL, 0),
    ('Hog Plums', 'Fruits', NULL, 0),
    ('Honeyberries', 'Fruits', NULL, 0),
    ('Honey Crisp Apples', 'Fruits', NULL, 0),
    ('Honeydew Melon', 'Fruits', NULL, 0),
    ('Honey Locust', 'Fruits', NULL, 0),
    ('Honeysuckles', 'Fruits', NULL, 0),
    ('Horned Melon', 'Fruits', NULL, 0),
    ('Huckleberry', 'Fruits', NULL, 0),
    ('Huito', 'Fruits', NULL, 0),
    ('Husk Tomatoes', 'Fruits', NULL, 0),
    ('Hyuganatsu', 'Fruits', NULL, 0),
    ('Imbe', 'Fruits', NULL, 0),
    ('Icacina', 'Fruits', NULL, 0),
    ('Iboga', 'Fruits', NULL, 0),
    ('Icaco', 'Fruits', NULL, 0),
    ('Indian Jujube Fruit', 'Fruits', NULL, 0),
    ('Indian Prune', 'Fruits', NULL, 0),
    ('Indian Sherbet Berry', 'Fruits', NULL, 0),
    ('Ice Apple', 'Fruits', NULL, 0),
    ('Indonesian Lime', 'Fruits', NULL, 0),
    ('Ilama', 'Fruits', NULL, 0),
    ('Ita Palm Fruit', 'Fruits', NULL, 0),
    ('Indian Almond Fruit', 'Fruits', NULL, 0),
    ('Imbu', 'Fruits', NULL, 0),
    ('Incaberry', 'Fruits', NULL, 0),
    ('Ice Cream Bean Fruit', 'Fruits', NULL, 0),
    ('Ichigo', 'Fruits', NULL, 0),
    ('Illawarra Plum', 'Fruits', NULL, 0),
    ('Indian Gooseberry', 'Fruits', NULL, 0),
    ('Indian Persimmon', 'Fruits', NULL, 0),
    ('Jackfruit', 'Fruits', NULL, 0),
    ('Jamun Plum', 'Fruits', NULL, 0),
    ('Japanese Persimmon', 'Fruits', NULL, 0),
    ('Japanese Plum', 'Fruits', NULL, 0),
    ('Jatoba t', 'Fruits', NULL, 0),
    ('Java Apple', 'Fruits', NULL, 0),
    ('Jazz Apples', 'Fruits', NULL, 0),
    ('Jelly Palm Fruit', 'Fruits', NULL, 0),
    ('Johannisbeere', 'Fruits', NULL, 0),
    ('Jostaberry', 'Fruits', NULL, 0),
    ('Juicy Tomatoes', 'Fruits', NULL, 0),
    ('Jujube Fruit', 'Fruits', NULL, 0),
    ('Junglesop Fruit', 'Fruits', NULL, 0),
    ('Juniper Berries', 'Fruits', NULL, 0),
    ('Kabosu', 'Fruits', NULL, 0),
    ('Kaffir Lime', 'Fruits', NULL, 0),
    ('Kahikatea', 'Fruits', NULL, 0),
    ('Kakadu Plum', 'Fruits', NULL, 0),
    ('Kaki Persimmon', 'Fruits', NULL, 0),
    ('Kanzi Apple', 'Fruits', NULL, 0),
    ('Karonda Berry', 'Fruits', NULL, 0),
    ('Kasturi Mango', 'Fruits', NULL, 0),
    ('Kawakawa', 'Fruits', NULL, 0),
    ('Kaywa', 'Fruits', NULL, 0),
    ('Kei Apple.', 'Fruits', NULL, 0),
    ('Keitt Mango', 'Fruits', NULL, 0),
    ('Key Lime', 'Fruits', NULL, 0),
    ('Kiwano', 'Fruits', NULL, 0),
    ('Kiwi', 'Fruits', NULL, 0),
    ('Knobby Russet Apple', 'Fruits', NULL, 0),
    ('Korean Pear', 'Fruits', NULL, 0),
    ('Korlan', 'Fruits', NULL, 0),
    ('Kowai', 'Fruits', NULL, 0),
    ('Kumquats', 'Fruits', NULL, 0),
    ('Kutjera Fruit', 'Fruits', NULL, 0),
    ('Kvede', 'Fruits', NULL, 0),
    ('Kwai Muk', 'Fruits', NULL, 0),
    ('Kyoho Grape', 'Fruits', NULL, 0),
    ('Lablab Fruit', 'Fruits', NULL, 0),
    ('Lady Apple', 'Fruits', NULL, 0),
    ('Lady Finger Banana', 'Fruits', NULL, 0),
    ('Lambkin Melon', 'Fruits', NULL, 0),
    ('Lancetilla Mango', 'Fruits', NULL, 0),
    ('Langra Mango', 'Fruits', NULL, 0),
    ('Langsat', 'Fruits', NULL, 0),
    ('Lapsi', 'Fruits', NULL, 0),
    ('Le Conte Pear', 'Fruits', NULL, 0),
    ('Lemato', 'Fruits', NULL, 0),
    ('Lemon Aspen', 'Fruits', NULL, 0),
    ('Lemon Drop Melon', 'Fruits', NULL, 0),
    ('Lemon', 'Fruits', NULL, 0),
    ('Liberty Apple', 'Fruits', NULL, 0),
    ('Lilly Pilly', 'Fruits', NULL, 0),
    ('Lima Orange', 'Fruits', NULL, 0),
    ('Limau Bali', 'Fruits', NULL, 0),
    ('Lime', 'Fruits', NULL, 0),
    ('Limeberry', 'Fruits', NULL, 0),
    ('Limquat', 'Fruits', NULL, 0),
    ('Lingonberry', 'Fruits', NULL, 0),
    ('Lippens Mango', 'Fruits', NULL, 0),
    ('Lodi Apple', 'Fruits', NULL, 0),
    ('Loganberry', 'Fruits', NULL, 0),
    ('Long Neck Avocado', 'Fruits', NULL, 0),
    ('Lord Lambourne Apple', 'Fruits', NULL, 0),
    ('Loquat', 'Fruits', NULL, 0),
    ('Louise Bonne of Jersey Pear', 'Fruits', NULL, 0),
    ('Lucuma', 'Fruits', NULL, 0),
    ('Macadamia Nut', 'Fruits', NULL, 0),
    ('Macoun Apple', 'Fruits', NULL, 0),
    ('Madison Peach', 'Fruits', NULL, 0),
    ('Madrono', 'Fruits', NULL, 0),
    ('Madrono', 'Fruits', NULL, 0),
    ('Mamey Sapote', 'Fruits', NULL, 0),
    ('Mammee Apple', 'Fruits', NULL, 0),
    ('Mamoncillo', 'Fruits', NULL, 0),
    ('Mandarin', 'Fruits', NULL, 0),
    ('Mangaba', 'Fruits', NULL, 0),
    ('Mango', 'Fruits', NULL, 0),
    ('Mangosteen', 'Fruits', NULL, 0),
    ('Maqui', 'Fruits', NULL, 0),
    ('Maracuya', 'Fruits', NULL, 0),
    ('Marang', 'Fruits', NULL, 0),
    ('Margil Apples', 'Fruits', NULL, 0),
    ('Marionberry', 'Fruits', NULL, 0),
    ('Marisol Clementine', 'Fruits', NULL, 0),
    ('Marsh Pink Grapefruit', 'Fruits', NULL, 0),
    ('Marula', 'Fruits', NULL, 0),
    ('May Apple', 'Fruits', NULL, 0),
    ('May Pride Peaches', 'Fruits', NULL, 0),
    ('Mayan Nut', 'Fruits', NULL, 0),
    ('Maypop', 'Fruits', NULL, 0),
    ('McIntosh Apple', 'Fruits', NULL, 0),
    ('Melon Pear Fruit', 'Fruits', NULL, 0),
    ('Merlot Grape', 'Fruits', NULL, 0),
    ('Meyer Lemon', 'Fruits', NULL, 0),
    ('Mexican Lime', 'Fruits', NULL, 0),
    ('Mexican Limes', 'Fruits', NULL, 0),
    ('Midyim Berry', 'Fruits', NULL, 0),
    ('Minneolo Tangelo', 'Fruits', NULL, 0),
    ('Miracle Fruit', 'Fruits', NULL, 0),
    ('Mock Strawberry', 'Fruits', NULL, 0),
    ('Monster Deliciosa', 'Fruits', NULL, 0),
    ('Naartjie', 'Fruits', NULL, 0),
    ('Nagami Kumquat', 'Fruits', NULL, 0),
    ('Nageia', 'Fruits', NULL, 0),
    ('Nam Dok Mai', 'Fruits', NULL, 0),
    ('Nance', 'Fruits', NULL, 0),
    ('Naranjilla', 'Fruits', NULL, 0),
    ('Narenj', 'Fruits', NULL, 0),
    ('Natal Plum', 'Fruits', NULL, 0),
    ('Nashi Pears', 'Fruits', NULL, 0),
    ('Naval Oranges', 'Fruits', NULL, 0),
    ('Nectacot', 'Fruits', NULL, 0),
    ('Nectacotum', 'Fruits', NULL, 0),
    ('Nectarines', 'Fruits', NULL, 0),
    ('Neem', 'Fruits', NULL, 0),
    ('Nepali Hog Plums', 'Fruits', NULL, 0),
    ('Nere Fruit', 'Fruits', NULL, 0),
    ('Newton Pippin Apple', 'Fruits', NULL, 0),
    ('Nocera Grape', 'Fruits', NULL, 0),
    ('Nopal Fruit', 'Fruits', NULL, 0),
    ('Northern Spy Apples', 'Fruits', NULL, 0),
    ('Nungu Fruit', 'Fruits', NULL, 0),
    ('Nutmeg', 'Fruits', NULL, 0),
    ('Nuts', 'Fruits', NULL, 0),
    ('O’Henry Peach', 'Fruits', NULL, 0),
    ('Oeillade Noire Grape', 'Fruits', NULL, 0),
    ('Ogallala Strawberry', 'Fruits', NULL, 0),
    ('Ogeechee Lime', 'Fruits', NULL, 0),
    ('Oil Palm', 'Fruits', NULL, 0),
    ('Okra', 'Fruits', NULL, 0),
    ('Okuzgozu Grape', 'Fruits', NULL, 0),
    ('Olallieberry', 'Fruits', NULL, 0),
    ('Olive', 'Fruits', NULL, 0),
    ('Opal Apple', 'Fruits', NULL, 0),
    ('Opal Plum', 'Fruits', NULL, 0),
    ('Opuntia', 'Fruits', NULL, 0),
    ('Orange', 'Fruits', NULL, 0),
    ('Orangelo', 'Fruits', NULL, 0),
    ('Oregon Grape', 'Fruits', NULL, 0),
    ('Orient Melon', 'Fruits', NULL, 0),
    ('Orient Pear', 'Fruits', NULL, 0),
    ('Oriental Cherry', 'Fruits', NULL, 0),
    ('Orin Apple', 'Fruits', NULL, 0),
    ('Orlando Tangelo', 'Fruits', NULL, 0),
    ('Oroblanco', 'Fruits', NULL, 0),
    ('Ortanique', 'Fruits', NULL, 0),
    ('OSO Grande Strawberry', 'Fruits', NULL, 0),
    ('Osteen Mango', 'Fruits', NULL, 0),
    ('Otaheite Gooseberry', 'Fruits', NULL, 0),
    ('Oullins Gage Plum', 'Fruits', NULL, 0),
    ('Oval Kumquat', 'Fruits', NULL, 0),
    ('Ozark Beauty Strawberry', 'Fruits', NULL, 0),
    ('Ozark Gold Apple', 'Fruits', NULL, 0),
    ('Pacific Rose Apple', 'Fruits', NULL, 0),
    ('Palestinian Sweet Limes', 'Fruits', NULL, 0),
    ('Papaya', 'Fruits', NULL, 0),
    ('Parsonage Pears', 'Fruits', NULL, 0),
    ('Passion Fruit', 'Fruits', NULL, 0),
    ('Paw Paw', 'Fruits', NULL, 0),
    ('Peaches', 'Fruits', NULL, 0),
    ('Peach Palm Fruit', 'Fruits', NULL, 0),
    ('Pears', 'Fruits', NULL, 0),
    ('Pecan', 'Fruits', NULL, 0),
    ('Pequi Fruit', 'Fruits', NULL, 0),
    ('Persian Limes', 'Fruits', NULL, 0),
    ('Persimmons', 'Fruits', NULL, 0),
    ('Petit Rouge Grapes', 'Fruits', NULL, 0),
    ('Peumo Fruit', 'Fruits', NULL, 0),
    ('Pie Pumpkins', 'Fruits', NULL, 0),
    ('Pigeon Plum', 'Fruits', NULL, 0),
    ('Pigface Fruit', 'Fruits', NULL, 0),
    ('Pili Fruit', 'Fruits', NULL, 0),
    ('Pineapple', 'Fruits', NULL, 0),
    ('Pineberries', 'Fruits', NULL, 0),
    ('Pink Lady Apples', 'Fruits', NULL, 0),
    ('Pink Pearl Apples', 'Fruits', NULL, 0),
    ('Pink Pineapple', 'Fruits', NULL, 0),
    ('Pink Pomelo', 'Fruits', NULL, 0),
    ('Pinot Noir Grapes', 'Fruits', NULL, 0),
    ('Pinova Apples', 'Fruits', NULL, 0),
    ('Pitaya', 'Fruits', NULL, 0),
    ('Plantains', 'Fruits', NULL, 0),
    ('Plums', 'Fruits', NULL, 0),
    ('Plumcots', 'Fruits', NULL, 0),
    ('Pluots', 'Fruits', NULL, 0),
    ('Pomato', 'Fruits', NULL, 0),
    ('Pomegranate', 'Fruits', NULL, 0),
    ('Pomelo', 'Fruits', NULL, 0),
    ('Ponderosa Lemons', 'Fruits', NULL, 0),
    ('Prickly Pears', 'Fruits', NULL, 0),
    ('Prunes', 'Fruits', NULL, 0),
    ('Pumpkins', 'Fruits', NULL, 0),
    ('Quince', 'Fruits', NULL, 0),
    ('Quandong', 'Fruits', NULL, 0),
    ('Quararibea', 'Fruits', NULL, 0),
    ('Querina Apples', 'Fruits', NULL, 0),
    ('Quinault Strawberry', 'Fruits', NULL, 0),
    ('Queen Anne Cherry', 'Fruits', NULL, 0),
    ('Queen Apple', 'Fruits', NULL, 0),
    ('Queen’s Forelle Pear', 'Fruits', NULL, 0),
    ('Queen Tahiti Pineapple', 'Fruits', NULL, 0),
    ('Raisins', 'Fruits', NULL, 0),
    ('Rajka Apples', 'Fruits', NULL, 0),
    ('Rambai', 'Fruits', NULL, 0),
    ('Rambutan', 'Fruits', NULL, 0),
    ('Ramontchi', 'Fruits', NULL, 0),
    ('Rangpur Lime', 'Fruits', NULL, 0),
    ('Raspberry', 'Fruits', NULL, 0),
    ('Raspuri Mango', 'Fruits', NULL, 0),
    ('Rata', 'Fruits', NULL, 0),
    ('Red Banana', 'Fruits', NULL, 0),
    ('Red Bayberry', 'Fruits', NULL, 0),
    ('Red Delicious Apple', 'Fruits', NULL, 0),
    ('Red Grape', 'Fruits', NULL, 0),
    ('Red Huckleberry', 'Fruits', NULL, 0),
    ('Red Mombin', 'Fruits', NULL, 0),
    ('Red Mulberry', 'Fruits', NULL, 0),
    ('Red Passion Fruit', 'Fruits', NULL, 0),
    ('Red Pear', 'Fruits', NULL, 0),
    ('Redcurrant', 'Fruits', NULL, 0),
    ('Rhobs El Arsa', 'Fruits', NULL, 0),
    ('Riberry', 'Fruits', NULL, 0),
    ('Rocha pear', 'Fruits', NULL, 0),
    ('Rockmelon', 'Fruits', NULL, 0),
    ('Rollinia', 'Fruits', NULL, 0),
    ('Rose Apple', 'Fruits', NULL, 0),
    ('Rose Hip', 'Fruits', NULL, 0),
    ('Roselle', 'Fruits', NULL, 0),
    ('Rosigold Mango', 'Fruits', NULL, 0),
    ('Rough Lemon', 'Fruits', NULL, 0),
    ('Rumbus Parviflorus', 'Fruits', NULL, 0),
    ('Rumdul', 'Fruits', NULL, 0),
    ('Sand Cherry', 'Fruits', NULL, 0),
    ('Saigon Mango.', 'Fruits', NULL, 0),
    ('Salak', 'Fruits', NULL, 0),
    ('Santol', 'Fruits', NULL, 0),
    ('Satsuma Mandarin', 'Fruits', NULL, 0),
    ('Serviceberry', 'Fruits', NULL, 0),
    ('Shonan Gold', 'Fruits', NULL, 0),
    ('Sloe', 'Fruits', NULL, 0),
    ('Soncoya', 'Fruits', NULL, 0),
    ('Sour Cherry', 'Fruits', NULL, 0),
    ('Sour Plum', 'Fruits', NULL, 0),
    ('Soursop', 'Fruits', NULL, 0),
    ('Splendor Apple', 'Fruits', NULL, 0),
    ('Star Apple', 'Fruits', NULL, 0),
    ('Star Fruit', 'Fruits', NULL, 0),
    ('Strawberry', 'Fruits', NULL, 0),
    ('Strawberry Guava', 'Fruits', NULL, 0),
    ('Sudachi', 'Fruits', NULL, 0),
    ('Sugar Baby Watermelon', 'Fruits', NULL, 0),
    ('Sugar Berry', 'Fruits', NULL, 0),
    ('Sugar Plum', 'Fruits', NULL, 0),
    ('Sunset Apple', 'Fruits', NULL, 0),
    ('Sweet Granadilla', 'Fruits', NULL, 0),
    ('Sweet Lime', 'Fruits', NULL, 0),
    ('Tachibana Orange', 'Fruits', NULL, 0),
    ('Tamarillo', 'Fruits', NULL, 0),
    ('Tangelo', 'Fruits', NULL, 0),
    ('Tangerine', 'Fruits', NULL, 0),
    ('Tart Cherry', 'Fruits', NULL, 0),
    ('Tayberry', 'Fruits', NULL, 0),
    ('Taylor’s Gold Pear', 'Fruits', NULL, 0),
    ('Terap', 'Fruits', NULL, 0),
    ('Texas Persimmon', 'Fruits', NULL, 0),
    ('Thimberry', 'Fruits', NULL, 0),
    ('Tomatillo', 'Fruits', NULL, 0),
    ('Tompkins King Apple', 'Fruits', NULL, 0),
    ('Tommy Atkins Mango', 'Fruits', NULL, 0),
    ('Topaz Apple', 'Fruits', NULL, 0),
    ('Tourist Pineapple', 'Fruits', NULL, 0),
    ('Trifoliate Orange', 'Fruits', NULL, 0),
    ('Tropical Apricot', 'Fruits', NULL, 0),
    ('Ububese', 'Fruits', NULL, 0),
    ('Ugli Fruit', 'Fruits', NULL, 0),
    ('Ugni Berry', 'Fruits', NULL, 0),
    ('Umbu Fruit', 'Fruits', NULL, 0),
    ('Umbra Fruit', 'Fruits', NULL, 0),
    ('Urava Fruit', 'Fruits', NULL, 0),
    ('Usuma Fruit', 'Fruits', NULL, 0),
    ('Umeboshi', 'Fruits', NULL, 0),
    ('Uvilla Fruit', 'Fruits', NULL, 0),
    ('Vaccarese Grapes', 'Fruits', NULL, 0),
    ('Valencia Oranges', 'Fruits', NULL, 0),
    ('Valencia Pride Mango', 'Fruits', NULL, 0),
    ('Van Dyke Mango', 'Fruits', NULL, 0),
    ('Vanilla', 'Fruits', NULL, 0),
    ('Velvet Apple', 'Fruits', NULL, 0),
    ('Velvet Tamarind', 'Fruits', NULL, 0),
    ('Vespolina Grape', 'Fruits', NULL, 0),
    ('Vicar of Winkfield Pear', 'Fruits', NULL, 0),
    ('Victoria Plum', 'Fruits', NULL, 0),
    ('Villafranca Lemon', 'Fruits', NULL, 0),
    ('Voavanga Fruit', 'Fruits', NULL, 0),
    ('Volkamer Lemon', 'Fruits', NULL, 0),
    ('Wahoo', 'Fruits', NULL, 0),
    ('Walnut', 'Fruits', NULL, 0),
    ('Wampee', 'Fruits', NULL, 0),
    ('Water Apple', 'Fruits', NULL, 0),
    ('Water Chestnut', 'Fruits', NULL, 0),
    ('Watermelon', 'Fruits', NULL, 0),
    ('Wax Apple', 'Fruits', NULL, 0),
    ('Wax Gourd', 'Fruits', NULL, 0),
    ('Wealthy Apple', 'Fruits', NULL, 0),
    ('West Indian Cherry', 'Fruits', NULL, 0),
    ('Western Hackberry', 'Fruits', NULL, 0),
    ('White Aspen', 'Fruits', NULL, 0),
    ('White Currant', 'Fruits', NULL, 0),
    ('White-Flowered Gourd', 'Fruits', NULL, 0),
    ('White Mulberries', 'Fruits', NULL, 0),
    ('Wild Bacher Grape', 'Fruits', NULL, 0),
    ('Wild Banana', 'Fruits', NULL, 0),
    ('Custard Apple', 'Fruits', NULL, 0),
    ('Wild Lemon', 'Fruits', NULL, 0),
    ('Wild Lowbush Blueberry', 'Fruits', NULL, 0),
    ('Wild Mangosteen', 'Fruits', NULL, 0),
    ('Wild Orange', 'Fruits', NULL, 0),
    ('Wild Peach', 'Fruits', NULL, 0),
    ('Wild Strawberry', 'Fruits', NULL, 0),
    ('Wild Sugar Apple', 'Fruits', NULL, 0),
    ('Wild Water Lemon', 'Fruits', NULL, 0),
    ('Williams Pear', 'Fruits', NULL, 0),
    ('Winter Melon', 'Fruits', NULL, 0),
    ('Winter Squash', 'Fruits', NULL, 0),
    ('Wolf Berry', 'Fruits', NULL, 0),
    ('Xanthium Strumarium', 'Fruits', NULL, 0),
    ('Xarel-lo', 'Fruits', NULL, 0),
    ('Xerophyte', 'Fruits', NULL, 0),
    ('Xigua fruit', 'Fruits', NULL, 0),
    ('Ximenia Americana', 'Fruits', NULL, 0),
    ('Ximenia Caffra', 'Fruits', NULL, 0),
    ('Xinomavro', 'Fruits', NULL, 0),
    ('Xoconostle Cactus Fruit', 'Fruits', NULL, 0),
    ('Xylocarp', 'Fruits', NULL, 0),
    ('Ya Pear', 'Fruits', NULL, 0),
    ('Yali Pear', 'Fruits', NULL, 0),
    ('Yangmei', 'Fruits', NULL, 0),
    ('Yayat', 'Fruits', NULL, 0),
    ('Yellow Bell Peppers', 'Fruits', NULL, 0),
    ('Yellow Chili Pepper', 'Fruits', NULL, 0),
    ('Yellow Dragon Fruit', 'Fruits', NULL, 0),
    ('Yayat Palm', 'Fruits', NULL, 0),
    ('Yellow Apple', 'Fruits', NULL, 0),
    ('Yellow Guava', 'Fruits', NULL, 0),
    ('Yellow Passion Fruit', 'Fruits', NULL, 0),
    ('Yellow Plum', 'Fruits', NULL, 0),
    ('Yellow Sapote', 'Fruits', NULL, 0),
    ('Yellow Strawberry', 'Fruits', NULL, 0),
    ('Yellow Watermelon', 'Fruits', NULL, 0),
    ('Yemenite Citron', 'Fruits', NULL, 0),
    ('York Apple', 'Fruits', NULL, 0),
    ('Young Mango', 'Fruits', NULL, 0),
    ('Youngberry', 'Fruits', NULL, 0),
    ('Yucca', 'Fruits', NULL, 0),
    ('Yumberry', 'Fruits', NULL, 0),
    ('Yunnan Hackberry', 'Fruits', NULL, 0),
    ('Yuzu', 'Fruits', NULL, 0),
    ('Zabergau Reinette Apple', 'Fruits', NULL, 0),
    ('Zalzalak', 'Fruits', NULL, 0),
    ('Zante Currant', 'Fruits', NULL, 0),
    ('Zarzamora', 'Fruits', NULL, 0),
    ('Zawngtah', 'Fruits', NULL, 0),
    ('Zebra Melon', 'Fruits', NULL, 0),
    ('Zestar Apple', 'Fruits', NULL, 0),
    ('Zhe', 'Fruits', NULL, 0),
    ('Zierfandler Grape', 'Fruits', NULL, 0),
    ('Zig Zag Vine Fruit', 'Fruits', NULL, 0),
    ('Zill Mango', 'Fruits', NULL, 0),
    ('Zinfandel Grape', 'Fruits', NULL, 0),
    ('Ziziphus Mauritiana', 'Fruits', NULL, 0),
    ('Zucchini', 'Fruits', NULL, 0),
    ('Zweigelt Grape', 'Fruits', NULL, 0),
    ('Zwetschge', 'Fruits', NULL, 0);

-- Vegtables //////////////////////////////////////////////

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Acorn Squash', 'Vegetables', NULL, 0),
    ('Alfalfa Sprouts', 'Vegetables', NULL, 0),
    ('All Blue Potato', 'Vegetables', NULL, 0),
    ('Amaranth', 'Vegetables', NULL, 0),
    ('Ambercup Squash', 'Vegetables', NULL, 0),
    ('Anise', 'Vegetables', NULL, 0),
    ('Artichoke', 'Vegetables', NULL, 0),
    ('Arugula', 'Vegetables', NULL, 0),
    ('Ash Gourd', 'Vegetables', NULL, 0),
    ('Asparagus', 'Vegetables', NULL, 0),
    ('Avocado', 'Vegetables', NULL, 0),
    ('Adzuki Bean', 'Vegetables', NULL, 0),
    ('Ahipa', 'Vegetables', NULL, 0),
    ('Aonori', 'Vegetables', NULL, 0),
    ('Arame', 'Vegetables', NULL, 0),
    ('Arikara Squash', 'Vegetables', NULL, 0),
    ('Arrowroot', 'Vegetables', NULL, 0),
    ('Asian Greens', 'Vegetables', NULL, 0),
    ('Ash Gourd', 'Vegetables', NULL, 0),
    ('Azuki Bean', 'Vegetables', NULL, 0),
    ('Baby Boo Pumpkin', 'Vegetables', NULL, 0),
    ('Bamboo Shoot', 'Vegetables', NULL, 0),
    ('Banana Pepper', 'Vegetables', NULL, 0),
    ('Banana Squash', 'Vegetables', NULL, 0),
    ('Basil', 'Vegetables', NULL, 0),
    ('Bean Sprout', 'Vegetables', NULL, 0),
    ('Beet', 'Vegetables', NULL, 0),
    ('Belgian Endive', 'Vegetables', NULL, 0),
    ('Bell Pepper', 'Vegetables', NULL, 0),
    ('Bintje Potato', 'Vegetables', NULL, 0),
    ('Bitter Melon', 'Vegetables', NULL, 0),
    ('Black Bean', 'Vegetables', NULL, 0),
    ('Black-Eyed Pea', 'Vegetables', NULL, 0),
    ('Black Radish', 'Vegetables', NULL, 0),
    ('Black Salsify', 'Vegetables', NULL, 0),
    ('Bok Choy', 'Vegetables', NULL, 0),
    ('Boniato', 'Vegetables', NULL, 0),
    ('Borage', 'Vegetables', NULL, 0),
    ('Borlotti Bean', 'Vegetables', NULL, 0),
    ('Boston Morrow Squash', 'Vegetables', NULL, 0),
    ('Broad Beans', 'Vegetables', NULL, 0),
    ('Broad-Leaf Arrowhead', 'Vegetables', NULL, 0),
    ('Broccoflower', 'Vegetables', NULL, 0),
    ('Broccoli', 'Vegetables', NULL, 0),
    ('Broccolini', 'Vegetables', NULL, 0),
    ('Brussels Sprout', 'Vegetables', NULL, 0),
    ('Burdock Root', 'Vegetables', NULL, 0),
    ('Butterhead Lettuce', 'Vegetables', NULL, 0),
    ('Butter Bean', 'Vegetables', NULL, 0),
    ('Butternut Squash', 'Vegetables', NULL, 0),
    ('Cabbage', 'Vegetables', NULL, 0),
    ('Cannellini Bean', 'Vegetables', NULL, 0),
    ('Caraway', 'Vegetables', NULL, 0),
    ('Carnival Squash', 'Vegetables', NULL, 0),
    ('Carrot', 'Vegetables', NULL, 0),
    ('Cauliflower', 'Vegetables', NULL, 0),
    ('Cayenne Pepper', 'Vegetables', NULL, 0),
    ('Celeriac', 'Vegetables', NULL, 0),
    ('Celery', 'Vegetables', NULL, 0),
    ('Chamomile', 'Vegetables', NULL, 0),
    ('Chard', 'Vegetables', NULL, 0),
    ('Cheddar Cauliflower', 'Vegetables', NULL, 0),
    ('Cherry Pepper', 'Vegetables', NULL, 0),
    ('Chickpeas', 'Vegetables', NULL, 0),
    ('Chili Pepper', 'Vegetables', NULL, 0),
    ('Chives', 'Vegetables', NULL, 0),
    ('Collard Greens', 'Vegetables', NULL, 0),
    ('Coriander', 'Vegetables', NULL, 0),
    ('Corms', 'Vegetables', NULL, 0),
    ('Corn', 'Vegetables', NULL, 0),
    ('Cucumber', 'Vegetables', NULL, 0),
    ('Cymbopogon', 'Vegetables', NULL, 0),
    ('Daikon', 'Vegetables', NULL, 0),
    ('Delicata', 'Vegetables', NULL, 0),
    ('Dickinson Pumpkin', 'Vegetables', NULL, 0),
    ('Dill', 'Vegetables', NULL, 0),
    ('Eddoe', 'Vegetables', NULL, 0),
    ('Eggplant', 'Vegetables', NULL, 0),
    ('Endive', 'Vegetables', NULL, 0),
    ('Fat Hen', 'Vegetables', NULL, 0),
    ('Fava Bean', 'Vegetables', NULL, 0),
    ('Fayot Bean', 'Vegetables', NULL, 0),
    ('Fennel', 'Vegetables', NULL, 0),
    ('Fiddlehead', 'Vegetables', NULL, 0),
    ('Field Cucumber', 'Vegetables', NULL, 0),
    ('Fiorentino Tomato', 'Vegetables', NULL, 0),
    ('Flat Beans', 'Vegetables', NULL, 0),
    ('Flat Italian Onion', 'Vegetables', NULL, 0),
    ('Flat White Boer Pumpkin', 'Vegetables', NULL, 0),
    ('Flint Corn', 'Vegetables', NULL, 0),
    ('Fluted Pumpkin', 'Vegetables', NULL, 0),
    ('French Bean', 'Vegetables', NULL, 0),
    ('French Sorrel', 'Vegetables', NULL, 0),
    ('Frisée', 'Vegetables', NULL, 0),
    ('Futsu Squash', 'Vegetables', NULL, 0),
    ('Garlic', 'Vegetables', NULL, 0),
    ('Gem Squash', 'Vegetables', NULL, 0),
    ('German Butterball Potato', 'Vegetables', NULL, 0),
    ('Gigante Bean', 'Vegetables', NULL, 0),
    ('Ginger', 'Vegetables', NULL, 0),
    ('Gold rush Squash', 'Vegetables', NULL, 0),
    ('Great Northern Bean', 'Vegetables', NULL, 0),
    ('Green Bean', 'Vegetables', NULL, 0),
    ('Habanero Pepper', 'Vegetables', NULL, 0),
    ('Honey Bear Squash', 'Vegetables', NULL, 0),
    ('Honeynut Squash', 'Vegetables', NULL, 0),
    ('Hot Pepper', 'Vegetables', NULL, 0),
    ('Hubbard Squash', 'Vegetables', NULL, 0),
    ('Jalapeño', 'Vegetables', NULL, 0),
    ('Japanese Sweet Potato', 'Vegetables', NULL, 0),
    ('Jerusalem Artichoke', 'Vegetables', NULL, 0),
    ('Jicama', 'Vegetables', NULL, 0),
    ('Kale', 'Vegetables', NULL, 0),
    ('Kelp', 'Vegetables', NULL, 0),
    ('Kidney Bean', 'Vegetables', NULL, 0),
    ('Kohlrabi', 'Vegetables', NULL, 0),
    ('Konjac', 'Vegetables', NULL, 0),
    ('Lavender', 'Vegetables', NULL, 0),
    ('Leek', 'Vegetables', NULL, 0),
    ('Lentil', 'Vegetables', NULL, 0),
    ('Lettuce', 'Vegetables', NULL, 0),
    ('Lima bean', 'Vegetables', NULL, 0),
    ('Lumina Pumpkin', 'Vegetables', NULL, 0),
    ('Malanga', 'Vegetables', NULL, 0),
    ('Mallow', 'Vegetables', NULL, 0),
    ('Mangelwurzel', 'Vegetables', NULL, 0),
    ('Mangetout', 'Vegetables', NULL, 0),
    ('Marjoram', 'Vegetables', NULL, 0),
    ('Miner’s Lettuce', 'Vegetables', NULL, 0),
    ('Molokhia', 'Vegetables', NULL, 0),
    ('Morels', 'Vegetables', NULL, 0),
    ('Mung Bean', 'Vegetables', NULL, 0),
    ('Mushroom', 'Vegetables', NULL, 0),
    ('Mustard Greens', 'Vegetables', NULL, 0),
    ('Navy Bean', 'Vegetables', NULL, 0),
    ('Nettle', 'Vegetables', NULL, 0),
    ('New Potato', 'Vegetables', NULL, 0),
    ('New Zealand Spinach', 'Vegetables', NULL, 0),
    ('Oak Leaf Lettuce', 'Vegetables', NULL, 0),
    ('Okra', 'Vegetables', NULL, 0),
    ('Onion', 'Vegetables', NULL, 0),
    ('Orange Bell Pepper', 'Vegetables', NULL, 0),
    ('Orange Tomato', 'Vegetables', NULL, 0),
    ('Oregano', 'Vegetables', NULL, 0),
    ('Paprika', 'Vegetables', NULL, 0),
    ('Parsnip', 'Vegetables', NULL, 0),
    ('Pattypan Squash', 'Vegetables', NULL, 0),
    ('Pea', 'Vegetables', NULL, 0),
    ('Peanut', 'Vegetables', NULL, 0),
    ('Pepper', 'Vegetables', NULL, 0),
    ('Peruvian Purple Potato', 'Vegetables', NULL, 0),
    ('Pie Pumpkin', 'Vegetables', NULL, 0),
    ('Pinto Bean', 'Vegetables', NULL, 0),
    ('Potato', 'Vegetables', NULL, 0),
    ('Purple Asparagus', 'Vegetables', NULL, 0),
    ('Purple Bell Pepper', 'Vegetables', NULL, 0),
    ('Purple Brussels Sprout', 'Vegetables', NULL, 0),
    ('Purple Cabbage', 'Vegetables', NULL, 0),
    ('Purple Carrot', 'Vegetables', NULL, 0),
    ('Purple Cauliflower', 'Vegetables', NULL, 0),
    ('Purple Corn', 'Vegetables', NULL, 0),
    ('Purple Kale', 'Vegetables', NULL, 0),
    ('Purple Lettuce', 'Vegetables', NULL, 0),
    ('Purple Majesty Potato', 'Vegetables', NULL, 0),
    ('Purple Radish', 'Vegetables', NULL, 0),
    ('Purple String Bean', 'Vegetables', NULL, 0),
    ('Purple Tomato', 'Vegetables', NULL, 0),
    ('Radicchio', 'Vegetables', NULL, 0),
    ('Radish', 'Vegetables', NULL, 0),
    ('Red Bell Pepper', 'Vegetables', NULL, 0),
    ('Red Bliss Potato', 'Vegetables', NULL, 0),
    ('Red Cabbage', 'Vegetables', NULL, 0),
    ('Red Carrot', 'Vegetables', NULL, 0),
    ('Red Gold Potato', 'Vegetables', NULL, 0),
    ('Red Kuri Squash', 'Vegetables', NULL, 0),
    ('Red Onion', 'Vegetables', NULL, 0),
    ('Red Russian Kale', 'Vegetables', NULL, 0),
    ('Red Warty Thing Squash', 'Vegetables', NULL, 0),
    ('Red Wing Onion', 'Vegetables', NULL, 0),
    ('Rhubarb', 'Vegetables', NULL, 0),
    ('Rosemary', 'Vegetables', NULL, 0),
    ('Runner Bean', 'Vegetables', NULL, 0),
    ('Russian Banana Potato', 'Vegetables', NULL, 0),
    ('Rutabaga', 'Vegetables', NULL, 0),
    ('Salsify', 'Vegetables', NULL, 0),
    ('Savoy Cabbage', 'Vegetables', NULL, 0),
    ('Scallion', 'Vegetables', NULL, 0),
    ('Shallot', 'Vegetables', NULL, 0),
    ('Skirret', 'Vegetables', NULL, 0),
    ('Snap Pea', 'Vegetables', NULL, 0),
    ('Soybean', 'Vegetables', NULL, 0),
    ('Spaghetti Squash', 'Vegetables', NULL, 0),
    ('Spinach', 'Vegetables', NULL, 0),
    ('Split Pea', 'Vegetables', NULL, 0),
    ('Squash', 'Vegetables', NULL, 0),
    ('Stokes Purple Sweet Potato', 'Vegetables', NULL, 0),
    ('Sweet Corn', 'Vegetables', NULL, 0),
    ('Sweet Potato', 'Vegetables', NULL, 0),
    ('Tabasco Pepper', 'Vegetables', NULL, 0),
    ('Taro', 'Vegetables', NULL, 0),
    ('Tat Soi', 'Vegetables', NULL, 0),
    ('Thyme', 'Vegetables', NULL, 0),
    ('Tomatillo', 'Vegetables', NULL, 0),
    ('Tomato', 'Vegetables', NULL, 0),
    ('Topinambur', 'Vegetables', NULL, 0),
    ('Torpedo Onion', 'Vegetables', NULL, 0),
    ('Turnip', 'Vegetables', NULL, 0),
    ('Ube', 'Vegetables', NULL, 0),
    ('Udupi Mattu Gulla Eggplant.', 'Vegetables', NULL, 0),
    ('Ulluco', 'Vegetables', NULL, 0),
    ('Upland Cress', 'Vegetables', NULL, 0),
    ('Urad Bean', 'Vegetables', NULL, 0),
    ('Velvet Bean', 'Vegetables', NULL, 0),
    ('Vidalia Onion', 'Vegetables', NULL, 0),
    ('Vivaldi Potato', 'Vegetables', NULL, 0),
    ('Vitelotte Potato', 'Vegetables', NULL, 0),
    ('Wasabi', 'Vegetables', NULL, 0),
    ('Water Chestnut', 'Vegetables', NULL, 0),
    ('Watercress', 'Vegetables', NULL, 0),
    ('Wax Bean', 'Vegetables', NULL, 0),
    ('White 7 Pot Pepper', 'Vegetables', NULL, 0),
    ('White Asparagus', 'Vegetables', NULL, 0),
    ('White Bell Pepper', 'Vegetables', NULL, 0),
    ('White Corn', 'Vegetables', NULL, 0),
    ('Xi Lan Hua', 'Vegetables', NULL, 0),
    ('Xi Yang Ca', 'Vegetables', NULL, 0),
    ('Xà Lách', 'Vegetables', NULL, 0),
    ('Xanthosoma Sagittifolium', 'Vegetables', NULL, 0),
    ('Xanthosoma Brasiliense', 'Vegetables', NULL, 0),
    ('Yam', 'Vegetables', NULL, 0),
    ('Yellow Onion', 'Vegetables', NULL, 0),
    ('Yellow Summer Squash', 'Vegetables', NULL, 0),
    ('Yellow Tomato', 'Vegetables', NULL, 0),
    ('Yukon Gold Potato', 'Vegetables', NULL, 0),
    ('Zephyr Squash', 'Vegetables', NULL, 0),
    ('Zucchini', 'Vegetables', NULL, 0);

-- Fungi //////////////////////////////////////////////////

INSERT INTO ingredents (name, parent, child_parent, usages)
VALUES
    ('Lobster Mushrooms', 'Fungi', NULL, 0),
    ('Black Trumpet Mushrooms', 'Fungi', NULL, 0),
    ('Blazei Cap Mushrooms', 'Fungi', NULL, 0),
    ('Wood Ear Mushrooms', 'Fungi', NULL, 0),
    ('Maitake Mushrooms', 'Fungi', NULL, 0),
    ('Nameki Mushrooms', 'Fungi', NULL, 0),
    ('Shitake Mushrooms', 'Fungi', NULL, 0),
    ('Portabella Mushrooms', 'Fungi', NULL, 0),
    ('Porcini Mushrooms', 'Fungi', NULL, 0),
    ('Reishi Mushrooms', 'Fungi', NULL, 0),
    ('Oyster Mushrooms', 'Fungi', NULL, 0),
    ('Turkey Tail Mushrooms', 'Fungi', NULL, 0),
    ('Enoki Mushrooms', 'Fungi', NULL, 0),
    ('Matsutake Mushrooms', 'Fungi', NULL, 0),
    ('Mousseron Mushrooms', 'Fungi', NULL, 0),
    ('Bolete Mushrooms', 'Fungi', NULL, 0),
    ('Morel Mushrooms', 'Fungi', NULL, 0),
    ('Champignon Mushrooms', 'Fungi', NULL, 0),
    ('King Trumpet Mushrooms', 'Fungi', NULL, 0),
    ('Paddy Straw Mushrooms', 'Fungi', NULL, 0),
    ('Chanterelle Mushrooms', 'Fungi', NULL, 0),
    ('Saffron Milk Cap Mushrooms', 'Fungi', NULL, 0),
    ('Lions Mane Mushrooms', 'Fungi', NULL, 0),
    ('Cauliflower Mushrooms', 'Fungi', NULL, 0);
